ValueSet: ConsentPolicyPurpose
Id: ConsentPolicyPurposeVS
* insert meta-profile
* ^url = "https://ths-greifswald.de/fhir/ValueSet/gics/ConsentPolicyPurpose"
* ^compose.include[0].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.timestamp = "2022-09-09T12:00:00Z"
* ^expansion.total = 26
* ^expansion.contains[0].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Arzt
* ^expansion.contains[=].display = "Arzt"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #CRO
* ^expansion.contains[=].display = "CRO"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Datenergaenzung
* ^expansion.contains[=].display = "Datenergaenzung"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Dritte
* ^expansion.contains[=].display = "Dritte"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #EU_DSGVO_NIVEAU
* ^expansion.contains[=].display = "EU_DSGVO_NIVEAU"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #non_EU_DSGVO_NIVEAU
* ^expansion.contains[=].display = "non_EU_DSGVO_NIVEAU"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Hausarzt
* ^expansion.contains[=].display = "Hausarzt"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #intern
* ^expansion.contains[=].display = "intern"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Krankenunterlagen
* ^expansion.contains[=].display = "Krankenunterlagen"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Monitoring
* ^expansion.contains[=].display = "Monitoring"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #non_profit
* ^expansion.contains[=].display = "non_profit"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #pharma
* ^expansion.contains[=].display = "pharma"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #prospektiv
* ^expansion.contains[=].display = "prospektiv"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #retrospektiv
* ^expansion.contains[=].display = "retrospektiv"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Vorhaben_spezifisch
* ^expansion.contains[=].display = "Vorhaben_spezifisch"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Vorhaben_intern
* ^expansion.contains[=].display = "Vorhaben_intern"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Vorhaben_Teilnahme
* ^expansion.contains[=].display = "Vorhaben_Teilnahme"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Tod
* ^expansion.contains[=].display = "Tod"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #uneingeschraenkt
* ^expansion.contains[=].display = "uneingeschraenkt"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #zeitlich_eingeschraenkt
* ^expansion.contains[=].display = "zeitlich_eingeschraenkt"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Verknuepfung_Datenbanken
* ^expansion.contains[=].display = "Verknuepfung_Datenbanken"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #weitere_Erhebungen
* ^expansion.contains[=].display = "weitere_Erhebungen"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #weitere_Studien
* ^expansion.contains[=].display = "weitere_Studien"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #Zufallsbefunde
* ^expansion.contains[=].display = "Zufallsbefunde"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #KV
* ^expansion.contains[=].display = "KV"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyPurpose"
* ^expansion.contains[=].code = #RV
* ^expansion.contains[=].display = "RV"
