ValueSet: ConsentPolicyAction
Id: ConsentPolicyActionVS
* insert meta-profile
* ^url = "https://ths-greifswald.de/fhir/ValueSet/gics/ConsentPolicyAction"
* ^compose.include[0].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.timestamp = "2022-09-09T12:00:00Z"
* ^expansion.total = 14
* ^expansion.contains[0].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #bereitstellen
* ^expansion.contains[=].display = "bereitstellen"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #uebertragen_eigentum
* ^expansion.contains[=].display = "uebertragen_eigentum"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #einsehen
* ^expansion.contains[=].display = "einsehen"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #entnehmen
* ^expansion.contains[=].display = "entnehmen"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #erheben
* ^expansion.contains[=].display = "erheben"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #analysieren_genetisch
* ^expansion.contains[=].display = "analysieren_genetisch"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #informieren
* ^expansion.contains[=].display = "informieren"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #lagern
* ^expansion.contains[=].display = "lagern"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #lagern_verarbeiten
* ^expansion.contains[=].display = "lagern_verarbeiten"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #rekontaktieren
* ^expansion.contains[=].display = "rekontaktieren"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #speichern
* ^expansion.contains[=].display = "speichern"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #speichern_verarbeiten
* ^expansion.contains[=].display = "speichern_verarbeiten"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #wissenschaftlich_nutzen
* ^expansion.contains[=].display = "wissenschaftlich_nutzen"
* ^expansion.contains[+].system = "https://ths-greifswald.de/fhir/CodeSystem/ConsentPolicyAction"
* ^expansion.contains[=].code = #zusammenfuehren
* ^expansion.contains[=].display = "zusammenfuehren"
