canonical: https://ths-greifswald.de/fhir
version: 2024.3.0-DEVEL
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.einwilligungsmanagement: 1.1.0-alpha.1
